src/objects/Blog__c.object
<CustomObject>
    <description>A Blog holds a number of Entry objects. In addition, a Blog also contains a Name and some administrative information regarding its usage - such as the number of entries to display and a checkbox that determines if a Blog is the default blog.</description>
    <fields>
        <fullName>Sort_Id__c</fullName>
        <label>Sort Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SiteSideBarController.cls
public without sharing class SiteSideBarController { // THis is specifically marked as without sharing so that we can read the orgName.

	public SiteSideBarController() {
		if (lastUpdate == null || lastUpdate.addMinutes(10) < Datetime.now()) {
			organizationName = [SELECT Name FROM Organization].Name;
			blogList = [SELECT Id, Name FROM Blog__c ORDER By Sort_id__c]; // query to find all blogs.
			lastUpdate = Datetime.now();
		}
	}
	
	public static List<Blog__c> blogList { get; set; }
	public static String organizationName  { get; set; }
	public static DateTime lastUpdate { get; set; }

	static testmethod void TestSideBarController() {
		//
	}
	
}