src/objects/Blog__c.object
<CustomObject>
    <description>A Blog holds a number of Entry objects. In addition, a Blog also contains a Name and some administrative information regarding its usage - such as the number of entries to display and a checkbox that determines if a Blog is the default blog.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</description>
        <inlineHelpText>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this the default blog associated with your site?</description>
        <inlineHelpText>Is this the default blog associated with your site?</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entries_to_Display__c</fullName>
        <description>The number of entries displayed by default.</description>
        <inlineHelpText>The number of entries displayed by default.</inlineHelpText>
        <label>Entries Displayed</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sidebar__c</fullName>
        <description>The HTML for the sidebar. (This should remain hidden. A Trigger on Entry save updates this.)</description>
        <label>Sidebar</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>rss_path__c</fullName>
        <description>The url to the RSS feed (if it has been setup.)</description>
        <label>RSS Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BlogLink__c.object
<CustomObject>
    <description>Website links that are displayed on the sidebar.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog to which this link is associated.</description>
        <inlineHelpText>The blog to which this link is associated.</inlineHelpText>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>BlogLinks</relationshipLabel>
        <relationshipName>BlogLinks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL to which this weblink points.</description>
        <inlineHelpText>The URL to which this weblink points.</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>BlogLink</label>
    <nameField>
        <label>Weblink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlogLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cMonth__c.object
<CustomObject>
    <description>cMonths are objects that associate entries with dates without having to do lookups on the created/posted dates.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this cMonth is associated with. You may have multiple cMonth objects all named the same - this is normal as each blog may have the same month/year combos if they&apos;re published regularly.</description>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>cMonth__c</relationshipLabel>
        <relationshipName>cMonths</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the month.</description>
        <label>Display Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date that this month item was created, we use it to order data. Sometimes we&apos;ll change these to move around display orders...</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Year_Name__c</fullName>
        <description>The year name that this cMonth is associated with.</description>
        <label>Year Name</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cYear__c</fullName>
        <description>The cYear that this cMonth is related to.</description>
        <label>cYear</label>
        <referenceTo>cYear__c</referenceTo>
        <relationshipLabel>cMonths</relationshipLabel>
        <relationshipName>cMonths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>cMonth</label>
    <nameField>
        <label>cMonth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cMonths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/cYear__c.object
<CustomObject>
    <description>cYear is a shortcut object for association entries with years without having to reference/comb through dates.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this cYear is associate with. You may have multiple cYear objects all named the same - this is normal as each blog may have the same month/year combos if they&apos;re published regularly.</description>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>cYears</relationshipLabel>
        <relationshipName>cYears</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>cYear</label>
    <nameField>
        <label>cYear Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cYears</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Entry__c.object
<CustomObject>
    <description>An entry that is associated with a blog.</description>
    <fields>
        <fullName>Abstract__c</fullName>
        <description>A short description of the content in your post.</description>
        <inlineHelpText>A short description of the content in your post.</inlineHelpText>
        <label>Abstract</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <description>Alias holds the posters name (or Alias) and can be displayed in the crumbs below entries.</description>
        <label>Alias</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this entry is related to.</description>
        <inlineHelpText>The blog that this entry is related to.</inlineHelpText>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>The body of the post. The blog engine will display any HTML characters input.</description>
        <inlineHelpText>The body of the post. The blog engine will display any HTML characters input.</inlineHelpText>
        <label>Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date and time that this entry was marked published.</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <label>Published</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cMonth__c</fullName>
        <description>The cMonth that this entry is related to.</description>
        <label>cMonth</label>
        <referenceTo>cMonth__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entry</label>
    <nameField>
        <label>Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/src/classes/BlogViewController.cls
/************************************************************
	BlogViewController - Controls the data and the view
	of blogs and entries on the sites pages.
************************************************************/
public with Sharing class BlogViewController {
	
	public List<Entry__c> recentEntries { get; set; } // just a list of tiltes
	public List<Entry__c> entryList { get; set; } // The full text of entires we'll display.
	public Blog__c pageBlog { get; set; } // the blog that we're referencing.
	public List<Blog__c> blogList { get; set; } // a list of other blogs (if any)
	public List<cMonth__c> monthlyId { get; set; } 
	public List<BlogLink__c> blogRoll { get; set; } // links/other blogs
	public String exp { get; set; } // The url date for the expandable side tree
	public Boolean render {get; set; } 
	public String errorMsg {get; set; }

	// Constructor.
	public BlogViewController() {
		// Vars.
		errorMsg = '';
		render = true;
		cYear__c yearTable = null; // If a specific year queried
		cMonth__c monthTable = null; // If a specific month queried
		cMonth__c[] completeMonths; // Will be used in an "IN" query.

		// Check the url and grab parameters
		// the ID is the blog id... 
		Id id = System.currentPageReference().getParameters().get('id');

		// We can filter by specific year/month/etc.
		String year = System.currentPageReference().getParameters().get('year');
		String month = System.currentPageReference().getParameters().get('month');
		
		// Controls if the accordion archive is or isn't expanded into the full tree.
		exp = '';
		exp = System.currentPageReference().getParameters().get('exp');
	
		// Get all blogs. THIS HAS MOVED TO THE SIDEBAR CONTROLLER!
		// blogList = [SELECT Id, Name FROM Blog__c]; // query to find all blogs.
		
		// If month is not null, but the year is null, set the month to null.
		if (month != null && year == null) {
			// Forget the date stuff. Disregard month.
			month = null;	
		}

		try {
			if (id == null) { 		
				pageBlog = [SELECT CreatedDate, Id, Name, RSS_Path__c, Allow_Comments__c, Sidebar__c, Entries_to_display__c, Default__c FROM Blog__c WHERE Default__c = true ORDER BY CreatedDate DESC LIMIT 1 ];
			} else {
				pageBlog = [SELECT Id, Name, RSS_Path__c, Allow_Comments__c, Sidebar__c, Entries_to_display__c FROM Blog__c WHERE Id = :id ];
			}
		} catch (Exception e) {
			// No blog found, toss an exception.
			errorMsg = 'No Default Blog Selected';
			render = false;
			return;
			//throw e;
		}
		
		// Setting up the "dates" that we'll use to query for entries below.
		if (year != null) { 
			yearTable = [SELECT Name, Id, Blog__c FROM cYear__c WHERE Blog__c = :pageBlog.id AND Name = :year]; 
			if (month != null) {
				monthTable = [SELECT Name, Id, cYear__c FROM cMonth__c WHERE cYear__c = :yearTable.id AND Name = :month];
			} else {
				completeMonths = [SELECT Name, Id, cYear__c FROM cMonth__c WHERE cYear__c = :yearTable.id];
			}	
		}
		
		// Setting up the entries that will be displayed in main body. 
		if (year != null && month != null) {
			//Use the month table to query for entries.
			entryList = [SELECT Id, Name, Blog__c, Alias__c, CreatedById, cMonth__c, Abstract__c, Content__c, Published__c, Published_Date__c FROM Entry__c WHERE Published__c = 'Published' AND Blog__c = :pageBlog.id AND cMonth__c = :monthTable.id ORDER BY Published_Date__c DESC ];			
		} else if (year != null) {
			// Use all months via IN clause
			entryList = [SELECT Id, Name, Blog__c, Alias__c, CreatedById, Abstract__c, Content__c, Published__c, Published_Date__c FROM Entry__c WHERE Published__c = 'Published' AND Blog__c = :pageBlog.id AND cMonth__c IN :completeMonths ORDER BY Published_Date__c DESC ];			
		} else {
			// Query all entries
			entryList = [SELECT Id, Name, Blog__c, Alias__c, CreatedById, Abstract__c, Content__c, Published__c, Published_Date__c FROM Entry__c WHERE Published__c = 'Published' AND Blog__c = :pageBlog.id ORDER BY Published_Date__c DESC limit :pageBlog.Entries_to_display__c.intValue() ];
		}
		
		// We skip the display or the queries in the main body. Oh well.
		
		// Find the recent entries to display on the side bar.
		recentEntries = [SELECT Id, Name, Blog__c, Alias__c, CreatedById, Abstract__c, Content__c, Published__c, Published_Date__c FROM Entry__c WHERE Published__c = 'Published' AND Blog__c = :pageBlog.id ORDER BY Published_Date__c DESC limit :pageBlog.Entries_to_display__c.intValue() ];
		blogRoll = [SELECT Name, URL__c, Blog__c, Number__c FROM BlogLink__c WHERE Blog__c = :pageBlog.Id ORDER BY Number__c ASC ];		
		
		// Set the monthlyList for valid months/years to display for Archives (used in JS tree on pages)
		//Get the valid months by querying the years related list by blogID. 
		// The JS that runs this is fairly complex - we pass in the months and use some script to read 
		// In a <UL> table from the Blog__c.Sidebar to display as a tree.
		monthlyId = [SELECT Id, Name, cYear__c, Year_Name__c, Display_Name__c, Published_Date__c FROM cMonth__c WHERE cYear__r.Blog__c = :pageBlog.id ORDER BY Published_Date__c DESC ]; 
	}

	static testmethod void testBlogViewController() {
		// Create a blog or use the default.
		Blog__c blog1;
		try {
			blog1 = [SELECT id,Allow_Comments__c,Entries_to_Display__c,Name,Default__c FROM Blog__c WHERE Default__c = true LIMIT 1];
		} catch (Exception e) {
			blog1 = new Blog__c();
		
			blog1.Allow_Comments__c = true;
			blog1.Default__c = true;
			blog1.Entries_to_Display__c = 10;
			blog1.Name = 'Blog 1';
			
			insert blog1;
		}

		System.assert(blog1.id != null); // Assert that blog has and id.


		// This will get the default blog, which is blog1 if there are no other blogs!
		System.currentPageReference().getParameters().put('id', blog1.id);
		BlogViewController bvc = new BlogViewController();
		System.assert(bvc.pageBlog.Id == blog1.Id);
		
		// Add a few entries.
		Entry__c entry1 = new Entry__c();
		entry1.Blog__c = blog1.Id;
		entry1.Published__c = 'Published';
		entry1.Content__c = 'test';
		entry1.Name = 'Entry 1';

		insert entry1;
		System.assert(entry1.id != null); // Assert that entry has and id.

		// Ensure that the Blog1 sidebar is not null now.
		BlogViewController bvc2 = new BlogViewController();
		System.assert(bvc2.pageBlog.Sidebar__c != null);
		
		// Call the page with a param.
		Pagereference page1 = Page.SiteBlogView;
		page1.getParameters().put('id', blog1.id);
		Test.setCurrentPageReference(page1);
		BlogViewController bvc3 = new BlogViewController();
		System.assert(bvc3.pageBlog.Id == blog1.Id);
		
		// Query by year
		page1.getParameters().put('year', String.valueOf(date.today().year()));
		Test.setCurrentPageReference(page1);
		BlogViewController bvc4 = new BlogViewController();
		System.assert(bvc4.entryList[0].id == entry1.Id);
		
		// Query by year and month
		page1.getParameters().put('month', BlogUtils.monthNameByMonthNumber(date.today().month()));
		Test.setCurrentPageReference(page1);
		BlogViewController bvc5 = new BlogViewController();
		System.assert(bvc5.entryList[0].id == entry1.Id);
	
	}

	
}