src/objects/Blog__c.object
<CustomObject>
    <description>A Blog holds a number of Entry objects. In addition, a Blog also contains a Name and some administrative information regarding its usage - such as the number of entries to display and a checkbox that determines if a Blog is the default blog.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</description>
        <inlineHelpText>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this the default blog associated with your site?</description>
        <inlineHelpText>Is this the default blog associated with your site?</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entries_to_Display__c</fullName>
        <description>The number of entries displayed by default.</description>
        <inlineHelpText>The number of entries displayed by default.</inlineHelpText>
        <label>Entries Displayed</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cMonth__c.object
<CustomObject>
    <description>cMonths are objects that associate entries with dates without having to do lookups on the created/posted dates.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this cMonth is associated with. You may have multiple cMonth objects all named the same - this is normal as each blog may have the same month/year combos if they&apos;re published regularly.</description>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>cMonth__c</relationshipLabel>
        <relationshipName>cMonths</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date that this month item was created, we use it to order data. Sometimes we&apos;ll change these to move around display orders...</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <label>cMonth</label>
    <nameField>
        <label>cMonth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cMonths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Entry__c.object
<CustomObject>
    <description>An entry that is associated with a blog.</description>
    <fields>
        <fullName>Abstract__c</fullName>
        <description>A short description of the content in your post.</description>
        <inlineHelpText>A short description of the content in your post.</inlineHelpText>
        <label>Abstract</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <description>Alias holds the posters name (or Alias) and can be displayed in the crumbs below entries.</description>
        <label>Alias</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this entry is related to.</description>
        <inlineHelpText>The blog that this entry is related to.</inlineHelpText>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>The body of the post. The blog engine will display any HTML characters input.</description>
        <inlineHelpText>The body of the post. The blog engine will display any HTML characters input.</inlineHelpText>
        <label>Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date and time that this entry was marked published.</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <label>Published</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cMonth__c</fullName>
        <description>The cMonth that this entry is related to.</description>
        <label>cMonth</label>
        <referenceTo>cMonth__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entry</label>
    <nameField>
        <label>Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/src/classes/SearchController.cls
public with sharing class SearchController {

	public List<Entry__c> entryList { get; set; }
	public Integer count { get; set; }
	public String errorMessage {get; set; }
	
	public String query { get; set; }
	
	public SearchController() {
		System.debug('*****: ' + System.currentPageReference().getParameters());
		
		// Vars.
		entryList = new List<Entry__c>();
		errorMessage = '';

		// Check the state data.
		query = System.currentPageReference().getParameters().get('q');
		if (query == null || query == '' || query.length() < 4) {
			// TODO no query to display. Reroute.	
			count = 0;
			if (query == null || query == '') {
				errorMessage = 'Query cannot be blank.';
			} else {
				errorMessage = 'Query must be more than 3 characters long.';
			}
						
		} else {
			// TODO the query is "contaminated". We need to filter out non-alphanumeric characters.
			// We need to filter out "KEYWORDS" such as SELECT and quotes.

			query = '*' + query + '*';

			// Setting up the entries that will be displayed in main body. 
			// Could we use a find?('*' +   + '*')
			List<List<SObject>> searchList = [FIND :query IN ALL FIELDS RETURNING relay__Entry__c (Id, Name, Blog__c, CreatedById, cMonth__c, Alias__c, Abstract__c, Content__c, Published__c, Published_Date__c WHERE Published__c = 'Published' ORDER BY Published_Date__c DESC) ];
			System.debug('*****: ' + searchList);
			// Iterate through the list of the objects...
			// for size of searchList, get the list of Entries.
			
			for (Integer j = 0; j < searchList.size(); j++) {
				List<SObject> entries = searchList[j];
				for (Integer i = 0; i < entries.size(); i++) {
					entryList.add((Entry__c) entries[i]); // Add entries to the list 
				}				
			}
			
			count = entryList.size();
		}
	}
	
	static testmethod void testSearchController() {
		// Create a blog.
		Blog__c blog1;
		try {
			blog1 = [SELECT id FROM Blog__c LIMIT 1];
		}
		catch (Exception e) {
			blog1 = new Blog__c();
			blog1.Allow_Comments__c = true;
			blog1.Default__c = true;
			blog1.Entries_to_Display__c = 10;
			blog1.Name = 'Blog 1';
			
			insert blog1;
		}
		// Add a few entries.
		Entry__c entry1 = new Entry__c();
		entry1.Blog__c = blog1.Id;
		entry1.Published__c = 'Published';
		entry1.Published_Date__c = Datetime.now();
		entry1.Content__c = 'makumozo';
		entry1.Name = 'Entry 1';

		insert entry1;
		
		System.debug('*************: ' + entry1.id);
		
		// Call the page with a blank param to just trigger the error.
		Pagereference page1 = Page.SiteSearch;
		page1.getParameters().put('q', '');
		Test.setCurrentPageReference(page1);
		SearchController sc1 = new SearchController();
		System.assert(sc1.errorMessage == 'Query cannot be blank.');
		
		// Query by year
		page1.getParameters().put('q', '123');
		Test.setCurrentPageReference(page1);
		SearchController sc2 = new SearchController();
		System.assert(sc2.errorMessage == 'Query must be more than 3 characters long.');
		
		// Query by year and month
		page1.getParameters().put('q', 'maku');
		Test.setCurrentPageReference(page1);
		SearchController sc3 = new SearchController();
		System.debug('***************: ' + sc3.query);
		System.debug('***************: ' + sc3.count);
		System.debug('***************: ' + sc3.entryList);
	}
	
}