src/objects/Blog__c.object
<CustomObject>
    <description>A Blog holds a number of Entry objects. In addition, a Blog also contains a Name and some administrative information regarding its usage - such as the number of entries to display and a checkbox that determines if a Blog is the default blog.</description>
    <label>Blog</label>
    <nameField>
        <label>Blog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Entry__c.object
<CustomObject>
    <description>An entry that is associated with a blog.</description>
    <fields>
        <fullName>Abstract__c</fullName>
        <description>A short description of the content in your post.</description>
        <inlineHelpText>A short description of the content in your post.</inlineHelpText>
        <label>Abstract</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this entry is related to.</description>
        <inlineHelpText>The blog that this entry is related to.</inlineHelpText>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>The body of the post. The blog engine will display any HTML characters input.</description>
        <inlineHelpText>The body of the post. The blog engine will display any HTML characters input.</inlineHelpText>
        <label>Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date and time that this entry was marked published.</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <label>Published</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Entry</label>
    <nameField>
        <label>Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AppiphonyPageController.cls
public class AppiphonyPageController {
	// This is a bit bogus and sad, but we have to set up independant items to 
	// take care of posting contents of entries back to the page. Not sure why...
	
	// The cases list is the body and titles of entries marked cases. 
    private List<Entry__c> cases;
	public List<Entry__c> getCases() {
		return cases;
	}
	
	private List<Entry__c> posts;
	private Entry__c post0;
	private Entry__c post1;
	private Entry__c post2;
	
	public Entry__c getPost0() {
		return posts[0];
	}
	public Entry__c getPost1() {
		return posts[1];
	}
	public Entry__c getPost2() {
		return posts[2];
	}


    public AppiphonyPageController () {
    	// IS there a way to get the latest entries off the page and into the site?
    	// Is there a way to wysiwyg the entry process?
        
       	// TODO mark as cases.
        // This just gets the relevant entries that are marked cases
    	cases = [SELECT Id, Name, CreatedById, Abstract__c, Content__c, Published__c, Published_Date__c FROM Entry__c WHERE Published__c = 'Published' AND Blog__c = 'a0b80000000dI6GAAU' ORDER BY Published_Date__c DESC limit 3];
		posts = [SELECT Id, Name FROM Entry__c WHERE Published__c = 'Published' AND Blog__c = 'a0b80000000dI6BAAU' ORDER BY Published_Date__c DESC limit 3]; 	
//		cases = new List<EntryDisplay>();
//		for (Integer i = 0; i < origCases.size(); i++) {
//			EntryDisplay entry = new EntryDisplay(origCases[i]);
//			cases.add(entry);
//		}				
    }
}