src/objects/Blog__c.object
<CustomObject>
    <description>A Blog holds a number of Entry objects. In addition, a Blog also contains a Name and some administrative information regarding its usage - such as the number of entries to display and a checkbox that determines if a Blog is the default blog.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</description>
        <inlineHelpText>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this the default blog associated with your site?</description>
        <inlineHelpText>Is this the default blog associated with your site?</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entries_to_Display__c</fullName>
        <description>The number of entries displayed by default.</description>
        <inlineHelpText>The number of entries displayed by default.</inlineHelpText>
        <label>Entries Displayed</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sidebar__c</fullName>
        <description>The HTML for the sidebar. (This should remain hidden. A Trigger on Entry save updates this.)</description>
        <label>Sidebar</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>rss_path__c</fullName>
        <description>The url to the RSS feed (if it has been setup.)</description>
        <label>RSS Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BlogLink__c.object
<CustomObject>
    <description>Website links that are displayed on the sidebar.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog to which this link is associated.</description>
        <inlineHelpText>The blog to which this link is associated.</inlineHelpText>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>BlogLinks</relationshipLabel>
        <relationshipName>BlogLinks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL to which this weblink points.</description>
        <inlineHelpText>The URL to which this weblink points.</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>BlogLink</label>
    <nameField>
        <label>Weblink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlogLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cMonth__c.object
<CustomObject>
    <description>cMonths are objects that associate entries with dates without having to do lookups on the created/posted dates.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this cMonth is associated with. You may have multiple cMonth objects all named the same - this is normal as each blog may have the same month/year combos if they&apos;re published regularly.</description>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>cMonth__c</relationshipLabel>
        <relationshipName>cMonths</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the month.</description>
        <label>Display Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date that this month item was created, we use it to order data. Sometimes we&apos;ll change these to move around display orders...</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Year_Name__c</fullName>
        <description>The year name that this cMonth is associated with.</description>
        <label>Year Name</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cYear__c</fullName>
        <description>The cYear that this cMonth is related to.</description>
        <label>cYear</label>
        <referenceTo>cYear__c</referenceTo>
        <relationshipLabel>cMonths</relationshipLabel>
        <relationshipName>cMonths</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>cMonth</label>
    <nameField>
        <label>cMonth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cMonths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Comment__c.object
<CustomObject>
    <description>A comment associated with an entry.</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>The text body of the comment.</description>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The posters email address</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entry__c</fullName>
        <description>The entry that this comment is associated with.</description>
        <label>Entry</label>
        <referenceTo>Entry__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sentinel__c</fullName>
        <description>Used to validate that a person is imputing data.</description>
        <label>Sentinel</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/cYear__c.object
<CustomObject>
    <description>cYear is a shortcut object for association entries with years without having to reference/comb through dates.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this cYear is associate with. You may have multiple cYear objects all named the same - this is normal as each blog may have the same month/year combos if they&apos;re published regularly.</description>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>cYears</relationshipLabel>
        <relationshipName>cYears</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>cYear</label>
    <nameField>
        <label>cYear Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>cYears</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Entry__c.object
<CustomObject>
    <description>An entry that is associated with a blog.</description>
    <fields>
        <fullName>Abstract__c</fullName>
        <description>A short description of the content in your post.</description>
        <inlineHelpText>A short description of the content in your post.</inlineHelpText>
        <label>Abstract</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <description>Alias holds the posters name (or Alias) and can be displayed in the crumbs below entries.</description>
        <label>Alias</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this entry is related to.</description>
        <inlineHelpText>The blog that this entry is related to.</inlineHelpText>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Close_Comment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, will not allow additional comments to be placed on the entry.</description>
        <inlineHelpText>If checked, will not allow additional comments to be placed on the entry.</inlineHelpText>
        <label>Close Comment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>The body of the post. The blog engine will display any HTML characters input.</description>
        <inlineHelpText>The body of the post. The blog engine will display any HTML characters input.</inlineHelpText>
        <label>Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date and time that this entry was marked published.</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <label>Published</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cMonth__c</fullName>
        <description>The cMonth that this entry is related to.</description>
        <label>cMonth</label>
        <referenceTo>cMonth__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entry</label>
    <nameField>
        <label>Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EntryViewController.cls
/************************************************************
	EntryViewController controls the view of entires on the
	sites pages
************************************************************/
public with Sharing class EntryViewController {

	// These variables are similar to the BlogViewController - check the comments there for more info.
	public Entry__c pageEntry { get; set; }
	public List<Entry__c> recentEntries { get; set; }
	public Blog__c pageBlog { get; set; }
	public List<BlogLink__c> blogRoll { get; set; }
	public List<Blog__c> blogList { get; set; }
	public List<cMonth__c> monthlyId { get; set; }
	public String captchaMsg { get; set; }
	public String exp { get; set; } // The statedata for the expandable side tree
	public Comment__c dummy { get; set; }
	public List<Comment__c> entryComments { get; set; } // The comments assoc with this entry.
	public Integer numComments {get; set;}
	public String plural {get; set;}
	
	public EntryViewController() {
		captchaMsg = '';
		
		Id id = System.currentPageReference().getParameters().get('id');

		exp = '';
		exp = System.currentPageReference().getParameters().get('exp');
		
		// Get the entry associated...
		pageEntry = [SELECT Id, Name, Alias__c, Blog__c, Close_Comment__c, CreatedById, Abstract__c, Content__c, Published__c, Published_Date__c FROM Entry__c WHERE Published__c = 'Published' AND Id = :id];
		
		// Get the comments associated...
		entryComments = [SELECT Id, Body__c, Email__c, CreatedDate FROM Comment__c WHERE Entry__c = :pageEntry.id ORDER BY CreatedDate ASC];
		numComments = entryComments.size();
		
		if (numComments == 1) {
			plural = '';
		} else {
			plural = 's';
		}
		
		// Look up the blog that this entry is associated with.
		pageBlog = [SELECT Id, RSS_Path__c, Name, Sidebar__c, Allow_Comments__c, Entries_to_display__c from Blog__c where Id = :pageEntry.Blog__c];
		
		// Look up the Additional recent cases.
		recentEntries = [SELECT Id, Name, Alias__c, CreatedById, Abstract__c, Content__c, Published__c, Published_Date__c FROM Entry__c WHERE Published__c = 'Published' AND Blog__c = :pageBlog.id ORDER BY Published_Date__c DESC limit :pageBlog.Entries_to_display__c.intValue()];			
		blogRoll = [SELECT Name, URL__c, Blog__c, Number__c FROM BlogLink__c WHERE Blog__c = :pageBlog.Id ORDER BY Number__c ASC ];		

		monthlyId = [SELECT Id, Name, cYear__c, CreatedDate, Year_Name__c, Display_Name__c FROM cMonth__c WHERE cYear__r.Blog__c = :pageEntry.Blog__c ORDER BY Published_Date__c DESC ]; 
	
		dummy = new Comment__c();
	}
	
	
	public PageReference postComment() {
		String headers='';
		String captchaChallenge;
		String captchaResponse;
        MAP<string, string> hdrs = ApexPages.CurrentPage().getParameters();
        for (string key : hdrs.keySet() ) {
            if (key == 'recaptcha_challenge_field') captchaChallenge = hdrs.get(key);
            if (key == 'recaptcha_response_field') captchaResponse = hdrs.get(key);
        }
		if (!captchaController.checkCaptcha(captchaChallenge, captchaResponse)) {
            captchaMsg = 'Invalid Captcha: Please Try Again';
          	
			return null;
		}
		
		// Take the input, and post a new comment
		dummy.Entry__c = pageEntry.Id;
		insert dummy;
		
		PageReference pref = Page.SiteEntryView;
		pref.getParameters().put('id', pageEntry.id);
		pref.getParameters().put('ck', String.valueOf(Datetime.now().getTime()));
		pref.setRedirect(true);
		
		return pref; 
	}

	static testmethod void testEntryViewController() {
		// Create a blog.
		
		Blog__c blog1;
		try {
			blog1 = [SELECT id FROM Blog__c LIMIT 1];
		} catch (Exception e) {
			blog1 = new Blog__c();
			blog1.Allow_Comments__c = true;
			blog1.Default__c = true;
			blog1.Entries_to_Display__c = 10;
			blog1.Name = 'Blog 1';
			insert blog1;
		}

		System.assert(blog1.id != null); // Assert that blog has and id.


		// Add a few entries.
		Entry__c entry1 = new Entry__c();
		entry1.Blog__c = blog1.Id;
		entry1.Published__c = 'Published';
		entry1.Content__c = 'test';
		entry1.Name = 'Entry 1';

		insert entry1;
		System.assert(entry1.id != null); // Assert that entry has and id.

		
		// Call the page with a param.
		Pagereference page1 = Page.SiteEntryView;
		page1.getParameters().put('id', entry1.id);
		Test.setCurrentPageReference(page1);
		EntryViewController evc3 = new EntryViewController();
		System.assert(evc3.pageEntry.id == entry1.id);
		
		evc3.dummy.Sentinel__c = '4';
		evc3.dummy.Body__c = 'test';
		evc3.dummy.Email__c = 'test@appiphony.com';
		PageReference commentReturn = evc3.postComment();
		System.assert(commentReturn == null); // will be null because callout not allowed
	}
}