src/objects/Blog__c.object
<CustomObject>
    <description>A Blog holds a number of Entry objects. In addition, a Blog also contains a Name and some administrative information regarding its usage - such as the number of entries to display and a checkbox that determines if a Blog is the default blog.</description>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</description>
        <inlineHelpText>If checked, the blog will support Relay&apos;s internal comment system. This is enabled by default.</inlineHelpText>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this the default blog associated with your site?</description>
        <inlineHelpText>Is this the default blog associated with your site?</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entries_to_Display__c</fullName>
        <description>The number of entries displayed by default.</description>
        <inlineHelpText>The number of entries displayed by default.</inlineHelpText>
        <label>Entries Displayed</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Comment__c.object
<CustomObject>
    <description>A comment associated with an entry.</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>The text body of the comment.</description>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The posters email address</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entry__c</fullName>
        <description>The entry that this comment is associated with.</description>
        <label>Entry</label>
        <referenceTo>Entry__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sentinel__c</fullName>
        <description>Used to validate that a person is imputing data.</description>
        <label>Sentinel</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Entry__c.object
<CustomObject>
    <description>An entry that is associated with a blog.</description>
    <fields>
        <fullName>Blog__c</fullName>
        <description>The blog that this entry is related to.</description>
        <inlineHelpText>The blog that this entry is related to.</inlineHelpText>
        <label>Blog</label>
        <referenceTo>Blog__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>The body of the post. The blog engine will display any HTML characters input.</description>
        <inlineHelpText>The body of the post. The blog engine will display any HTML characters input.</inlineHelpText>
        <label>Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <description>The date and time that this entry was marked published.</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <label>Published</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Entry</label>
    <nameField>
        <label>Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/src/classes/BlogTestHarness.cls
/************************************************************
	BlogTestHarness simply tests the comment and blog
	triggers.
************************************************************/
public class BlogTestHarness {

	static testmethod void makeBlogEntriesComments() {
		
		Blog__c blog1; // the blog we'll be adding items to. If there is a default blog, then use it, if not, create one.
		try {
			blog1 = [SELECT id, Default__c FROM Blog__c WHERE Default__c = true LIMIT 1];

		} catch (Exception e) {
			blog1 = new Blog__c();
			blog1.Allow_Comments__c = true;
			blog1.Default__c = true;
			blog1.Entries_to_Display__c = 10;
			blog1.Name = 'Blog Test 1';
			insert blog1;
		}

		System.assert(blog1.id != null); // Assert that blog has and id.
		

		List<Entry__c> entryList = new List<Entry__c>(); // A list of dummy entries.
		Entry__c entry1 = new Entry__c();

		for (Integer i=0; i < 100; i++) { // had to kick it to 100, since adding 200 would result in a over the limit issue...
			entry1 = new Entry__c();
			entry1.Blog__c = blog1.Id;
			entry1.Published__c = 'Published';
			entry1.Content__c = 'test';
			entry1.Name = 'Entry ' + i;
			entry1.Published_Date__c = Datetime.now();
			entryList.add(entry1);
		}

		insert entryList; // Insert the entries.

		// Have some way that the entries actually went through.
		for (Entry__c loopEntry : entryList) {
			System.assert(loopEntry.Id != null);
		}
				

		List<Comment__c> commentList = new List<Comment__c>(); // A list of comments that we'll add.	
		Comment__c comment = new Comment__c();
		for(Integer j=0; j < entryList.size(); j++) {
			comment = new Comment__c();
			//comment.Entry__c = entryList[j].Id;
			comment.Body__c = 'TESTING123';
			comment.Email__c = 'bob@bob.com';
			comment.Sentinel__c = '4';
			commentList.add(comment);
		}

		insert commentList;

		// Have some way that the entries actually went through.
		for (Comment__c loopComment : commentList) {
			System.assert(loopComment.Id != null);
		}

		delete blog1; // cascade a delete.	
		
	}

}