trunk/src/objects/Comment__c.object
<CustomObject>
    <description>A comment associated with an entry.</description>
    <fields>
        <fullName>Entry__c</fullName>
        <description>The entry that this comment is associated with.</description>
        <label>Entry</label>
        <referenceTo>Entry__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/Entry__c.object
<CustomObject>
    <description>An entry that is associated with a blog.</description>
    <label>Entry</label>
    <nameField>
        <label>Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/src/classes/lookupCommentsByEntryIdController.cls
public with sharing class lookupCommentsByEntryIdController {

	public String controllerValue { get;
		set {
			controllerValue = lookupCommentsByAnEntryId(value);
		}
	}
	
	public String lookupCommentsByAnEntryId(String id) {
		List<Id> CommentList = new List<Id>();
		try {
		for (Comment__c c : [SELECT Id FROM Comment__c WHERE Entry__c =: id]) {
			CommentList.add(c.Id);
		}
		}
		catch (Exception e) {
			//do nothing size will be 0
		}
		String returnVal;
		returnVal = (CommentList.size() == 1) ? CommentList.size() + ' Comment' : CommentList.size() + ' Comments';
		return returnVal;		
	}

	static testmethod void testLookUpEntryComment() {
		
		lookupCommentsByEntryIdController lua = new lookupCommentsByEntryIdController();
		lua.controllerValue = '';
	}
	
	
}